name: Pull Request Labels
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      
      - uses: actions/checkout@v4
      - name: LS folder
        run: |
            ls -lha
      - name: Extract appVersion
        run: |
          APP_VERSION=$(yq e '.appVersion' deploy/helm/Chart.yaml)
          echo "app_version=$APP_VERSION" >> $GITHUB_ENV

      # Dynamically generate labeler.yml
      - name: Generate labeler.yml
        run: |
          cat << EOF > .github/labeler.yml
          "${{ env.app_version }}":
            - changed-files:
              - any-glob-to-any-file: '**'
          EOF

      # Run the labeler
      - name: Run Labeler
        uses: actions/labeler@v4