name: Pull Request Labels
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      
      - uses: actions/checkout@v4
      - name: LS folder
        run: |
            ls -lha
      - name: Extract appVersion
        run: |
          APP_VERSION=$(yq e '.appVersion' deploy/helm/Chart.yaml)
          echo "app_version=$APP_VERSION" >> $GITHUB_ENV
      - uses: actions/labeler@v5