name: Labels
on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  version-label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Extract appVersion and Helm version
        run: |
          CHART_FILE=$(find deploy -type f -path '*/Chart.yaml')
          echo "APP_VERSION=$(yq e '.appVersion' $CHART_FILE)" >> $GITHUB_ENV
          echo "HELM_VERSION=$(yq e '.version' $CHART_FILE)" >> $GITHUB_ENV
      - name: Generate labeler.yml
        run: |
          cat << EOF > .github/labeler.yml
          "${{ env.APP_VERSION }}":
            - changed-files:
              - any-glob-to-any-file: '**'
          "helm: ${{ env.HELM_VERSION }}":
            - base-branch: 'main'
          EOF
      - name: Run Labeler
        uses: actions/labeler@v5