name: Pull Request Labels
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Extract appVersion
        id: extract_version
        run: |
          APP_VERSION=$(yq e '.appVersion' deploy/helm/Chart.yaml)
          echo "app_version=$APP_VERSION" >> $GITHUB_ENV
      - uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 1
          labels: |
            env.app_version