name: Pull Request Labels
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      
      - uses: actions/checkout@v4
      - name: LS folder
        run: |
            ls -lha
      - name: Extract appVersion
        run: |
          APP_VERSION=$(yq e '.appVersion' deploy/helm/Chart.yaml)
          echo "app_version=$APP_VERSION" >> $GITHUB_ENV

      # Dynamically add a label using the version number
      - name: Add Dynamic Label
        uses: actions/github-script@v6
        with:
          script: |
            const label = `semver:${process.env.app_version}`;
            const labels = await github.issues.listLabelsOnIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
            });

            const hasLabel = labels.data.some(l => l.name === label);
            if (!hasLabel) {
              await github.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                labels: [label],
              });
            }