name: Labels
on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  version-label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Extract appVersion and Helm version
        run: |
          CHART_FILE=$(find deploy -type f -path '*/Chart.yaml')
          echo "APP_VERSION=$(yq e '.appVersion' $CHART_FILE)" >> $GITHUB_ENV
          echo "HELM_VERSION=$(yq e '.version' $CHART_FILE)" >> $GITHUB_ENV
      - name: Generate labeler.yml
        run: |
          cat << EOF > .github/labeler.yml
          "release: ${{ env.APP_VERSION }}":
            - changed-files:
              - any-glob-to-any-file: '**'
          "chart: ${{ env.HELM_VERSION }}":
            - base-branch: 'main'
          EOF
      - name: Run Labeler
        uses: actions/labeler@v5
      - name: Set Label Colors
        run: |
          # Define label colors
          declare -A label_colors=(
            ["release"]="FF5733"
            ["chart"]="FFCC00"
          )
          
          for label in "${!label_colors[@]}"; do
            gh label edit "$label" --color "${label_colors[$label]}" || \
            gh label create "$label" --color "${label_colors[$label]}"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}